name: "Build xivlauncher-cn"

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Dotnet Restore
        working-directory: ./src/XIVLauncher.Core/
        run: dotnet restore

      - name: Dotnet Build (Default)
        working-directory: ./src/XIVLauncher.Core/
        run: |
          rm -rf bin
          dotnet build --configuration Release --no-restore

      - name: Upload Artifact (Default)
        uses: actions/upload-artifact@v3
        with:
          name: XIVLauncher.Core-default
          path: ./src/XIVLauncher.Core/bin/Release/net6.0

      - name: Dotnet Build (Ubuntu)
        working-directory: ./src/XIVLauncher.Core/
        run: |
          rm -rf bin
          dotnet publish -r linux-x64 --sc --configuration Release -p:DefineConstants=WINE_XIV_UBUNTU_LINUX --no-restore

      - name: Upload Artifacts (Ubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: XIVLauncher.Core-Ubuntu
          path: ./src/XIVLauncher.Core/bin/Release/net6.0/linux-x64/publish
