name: "pacstall-deb"

on:
  workflow_dispatch:

jobs:
  pacstall-makedeb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup pacstall
        run: sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"

      - name: pacstall Makedeb
        run: |
          git clone https://github.com/qy117121/xivlauncher-cn.git /tmp/xivlauncher-cn
          cd /tmp/xivlauncher-cn
          pacstall -I -B  -P ./xivlauncher-cn-git.pacscript
          mkdir deb
          mv *.deb deb/xivlauncher-cn-amd64.deb

      - name: Upload Artifacts (deb)
        uses: actions/upload-artifact@v3
        with:
          name: xivlauncher-cn.deb
          path: /tmp/xivlauncher-cn/deb/*.deb
